### ISSUE TITLE
Fix typos in jupyter notebook

### ISSUE THREAD

**Issue by gpsyrou** [gpsyrou/Twitter_Topic_Modelling#28]

**Comment by lamsi7** [comment]
Hi there,
can I help with this one?

**Comment by gpsyrou** [comment]
> Hi there,
> can I help with this one?

Sure! go for it! :)

**Comment by lamsi7** [comment]
Hi, 
I just want to check with you one thing. Since .ipynb files contain lots of metadata, it might be hard to see diffs in corrections later on. To avoid this, I was thinking to convert the file to, for example, .html and work on that. 
Do you have any preferences when it comes to file format? Would you rather have different file format for corrections purposes? Or should I maybe work on .ipynb anyway? 
Let me know what suits you best, thanks!

**Comment by gpsyrou** [comment]
Hello @lamsi7  - this is a good question. I would say you can implement the changes directly in the .ipynb file and then before I merge it I will do a proof read either way :) I pretty much know where changing are needed.

While you are reading the project, if you find anything that looks interesting and you would like to work on it let me know. Its a pretty open project, so if you have any ideas let me know!

**Comment by lamsi7** [comment]
Hello @gpsyrou,
sure, all clear now! Great, thanks for the info. I will have a look!
